config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/create'
  get 'posts/dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :image_url, presence: true
    validates :content, presence: true

    before_save :censura

    def censura
        palabras_censuradas = ["spoiler", "Spoiler", "SPOILER"]
        palabras_censuradas.each do |word|
           
            palabra_temporal = self.content.partition(/#{Regexp.quote(word)}/)
            
            if palabra_temporal[1] != ""
                self.content = palabra_temporal[0].concat(palabra_temporal[-1])
            end
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "12345", only: :dashboard
  
  def index
    @posts = Post.all
  end

  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])
  end

  def dashboard
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
        <div class="container">
          <a class="navbar-brand" href="<%= root_path %>">EL BLOG borra-espoiler</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/posts/dashboard">Inicia Sesion</a>
              </li>
             </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container pt-4">
        <%= yield %>
    </div>

  </body>

</html>

app/views/posts/create.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger mt-5" role="alert">
            <h4 class="alert-heading"><strong>Oh boy!</strong> something went wrong</h4>
            <p><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</p>
            <hr>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% else %>
    <div class="alert alert-success mt-5" role="alert">
      <h4 class="alert-heading">Well done!</h4>
      <p>Your post has been uploaded successfully !!!</p>
    </div>    
<% end %>

<div class="row">
    <div class="col">   
        <%= link_to "Go to Post Creation", posts_dashboard_path %>
    </div>
    <div class="col text-right">
        <%= link_to "Back to Index", root_path %>
    </div>
</div>

app/views/posts/dashboard.html.erb
<div class="container pt-5">

    <h1 class="text-center"> Bienvenido!! </h1>
    <h2 class="text-center"> Vamos a crear tu historia / post :</h2>

    <form id="create_posts" method="get" action="/posts/create">
        <div class="form-group">
            <label for="title">Titulo</label>
            <input name="title" class="form-control" placeholder="Ingresa un titulo para tu post">
        </div>

        <div class="form-group">
            <label for="image_url">Link Imagen</label>
            <input name="image_url" class="form-control" placeholder="ingresa el link que lleva a tu imagen">
        </div>

        <div class="form-group">
            <label for="content">Contenido</label>
            <textarea name="content" class="form-control"></textarea> 
        </div> 

        <div class="text-right">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>

    </form>
</div>

app/views/posts/index.html.erb
<% new_post = true %>
<% @posts.reverse.each do |post| %>
    <article class="card my-5">
        <%= image_tag post.image_url, :class=>"card-img-top", :height=>"400" %>
        <div class="card-body">
            <h5 class="card-title">
                <%= post.title %>
                <% if new_post %> 
                    <% new_post = false %>
                    <span class="badge badge-pill badge-success">New</span>
                <% end %>
            </h5>
            <p class="card-text"><%= post.content %></p>
            <p class="card-text"><small class="text-muted">Created at <%= post.created_at %></small></p>
        </div>
    </article>
<% end %>